import { createHash, randomUUID } from "node:crypto";
import { readFile } from "node:fs/promises";
import { extname, resolve } from "node:path";
import { RepositoryScanner, type RepositoryFile } from "../../repository/application/services/repository-import-service";
import type { CodeFile, CodeRelationship, CodeSymbol } from "../domain/entities/code-knowledge";
import { AnalysisJob } from "../domain/entities/analysis-job";

export interface StructuredKnowledgeStore { save(job: AnalysisJob, files: readonly CodeFile[], symbols: readonly CodeSymbol[], relationships: readonly CodeRelationship[]): Promise<void>; updateJob(job: AnalysisJob): Promise<void>; }
const id = (value: string) => createHash("sha256").update(value).digest("hex").slice(0, 24);
export class LanguageAnalyzer { public detect(extension: string): string { return ({ ".cs": "C#", ".java": "Java", ".ts": "TypeScript", ".tsx": "TypeScript", ".js": "JavaScript", ".jsx": "JavaScript", ".py": "Python", ".sql": "SQL" }[extension.toLowerCase()] ?? "Unknown"); } }
export class CSharpAnalyzer { public extract(repositoryId: string, file: CodeFile, content: string): readonly CodeSymbol[] { return [...content.matchAll(/\b(class|interface)\s+([A-Za-z_]\w*)/g)].map((match) => ({ id: id(`${file.id}:${match[2]}`), repositoryId, fileId: file.id, kind: match[1] === "interface" ? "interface" : "class", name: match[2], qualifiedName: match[2], line: content.slice(0, match.index).split("\n").length })); } }
export class TypeScriptAnalyzer { public extract(repositoryId: string, file: CodeFile, content: string): readonly CodeSymbol[] { return [...content.matchAll(/\b(class|interface|function)\s+([A-Za-z_$][\w$]*)/g)].map((match) => ({ id: id(`${file.id}:${match[2]}`), repositoryId, fileId: file.id, kind: match[1] as "class" | "interface" | "function", name: match[2], qualifiedName: match[2], line: content.slice(0, match.index).split("\n").length })); } }
export class SqlAnalyzer { public extract(repositoryId: string, file: CodeFile, content: string): readonly CodeSymbol[] { return [...content.matchAll(/\b(?:create\s+(?:table|view|procedure)|from|join)\s+([\w.\[\]]+)/gi)].map((match) => ({ id: id(`${file.id}:${match[1]}`), repositoryId, fileId: file.id, kind: "database-object", name: match[1], qualifiedName: match[1], line: content.slice(0, match.index).split("\n").length })); } }
export class AnalysisOrchestrator {
  public constructor(private readonly store: StructuredKnowledgeStore, private readonly scanner = new RepositoryScanner(), private readonly language = new LanguageAnalyzer(), private readonly csharp = new CSharpAnalyzer(), private readonly typescript = new TypeScriptAnalyzer(), private readonly sql = new SqlAnalyzer()) {}
  public async execute(repositoryId: string, workspace: string): Promise<AnalysisJob> { let job = new AnalysisJob(randomUUID(), repositoryId, "running", 0, "File discovery", new Date()); await this.store.updateJob(job); try { const scanned = await this.scanner.scan(workspace); const files = scanned.map((file) => this.file(repositoryId, file)); job = new AnalysisJob(job.id, repositoryId, "running", 30, "Symbol extraction", job.startedAt); await this.store.updateJob(job); const symbols: CodeSymbol[] = []; for (const file of files) { const content = await readFile(resolve(workspace, file.path), "utf8"); if (file.language === "C#") symbols.push(...this.csharp.extract(repositoryId, file, content)); else if (file.language === "TypeScript" || file.language === "JavaScript") symbols.push(...this.typescript.extract(repositoryId, file, content)); else if (file.language === "SQL") symbols.push(...this.sql.extract(repositoryId, file, content)); } job = new AnalysisJob(job.id, repositoryId, "running", 75, "Relationship mapping", job.startedAt); await this.store.updateJob(job); const relationships = this.relationships(repositoryId, symbols); job = new AnalysisJob(job.id, repositoryId, "completed", 100, "Structured knowledge stored", job.startedAt, new Date()); await this.store.save(job, files, symbols, relationships); return job; } catch (error) { job = new AnalysisJob(job.id, repositoryId, "failed", job.progress, "Analysis failed", job.startedAt, new Date(), error instanceof Error ? error.message : "Analysis failed."); await this.store.updateJob(job); return job; } }
  private file(repositoryId: string, scanned: RepositoryFile): CodeFile { const extension = extname(scanned.path).toLowerCase(); return Object.freeze({ id: id(`${repositoryId}:${scanned.path}`), repositoryId, path: scanned.path, extension, size: scanned.size, language: this.language.detect(extension) }); }
  private relationships(repositoryId: string, symbols: readonly CodeSymbol[]): readonly CodeRelationship[] { const byName = new Map(symbols.map((symbol) => [symbol.name, symbol])); return Object.freeze(symbols.flatMap((symbol) => symbol.kind === "class" && byName.has(`I${symbol.name}`) ? [{ id: id(`${symbol.id}:implements:${byName.get(`I${symbol.name}`)!.id}`), repositoryId, sourceSymbolId: symbol.id, targetSymbolId: byName.get(`I${symbol.name}`)!.id, kind: "implements" as const, confidence: 0.6 }] : [])); }
}
