"use client";
import { Activity, Database, Gauge, Timer } from "lucide-react";
import { useEffect, useState } from "react";
type Data = { job?: { status: string; progress: number; currentStep: string; error?: string }; performance: Record<string, number>; cachedAt?: string };
export function AnalysisDiagnostics({ repositoryId }: { readonly repositoryId: string }) {
  const [data, setData] = useState<Data>();
  useEffect(() => { const load = () => fetch(`/api/repositories/${repositoryId}/analysis/diagnostics`).then(async (response) => response.ok && setData(await response.json())); void load(); const timer = window.setInterval(load, 2000); return () => window.clearInterval(timer); }, [repositoryId]);
  if (!data) return <div className="space-y-4"><div className="skeleton h-10 w-56" /><div className="skeleton h-48" /></div>;
  const cards = [["Files analyzed", data.performance.filesAnalyzed ?? 0, Activity], ["Files skipped", data.performance.filesSkipped ?? 0, Database], ["Cache hit rate", `${data.performance.cacheHitRate ?? 0}%`, Gauge], ["Discovery time", data.performance.discoveryMs ? `${data.performance.discoveryMs} ms` : "—", Timer]] as const;
  return <section className="mx-auto max-w-5xl py-7"><p className="eyebrow">Developer diagnostics</p><h1 className="mt-2 text-2xl font-semibold">Analysis pipeline</h1><div className="mt-6 ariadne-panel p-5"><div className="flex items-center justify-between gap-4"><div><p className="font-medium">{data.job?.currentStep ?? "Analysis has not started"}</p><p className="mt-1 text-sm text-slate-500">{data.job?.status?.toLowerCase() ?? "waiting"}</p></div><span className="text-xl font-semibold text-cyan-200">{data.job?.progress ?? 0}%</span></div><div className="mt-4 h-2 overflow-hidden rounded-full bg-slate-800"><div className="h-full rounded-full bg-gradient-to-r from-violet-500 to-cyan-300 transition-all duration-500" style={{ width: `${data.job?.progress ?? 0}%` }} /></div>{data.job?.error && <p className="mt-3 text-sm text-rose-300">{data.job.error}</p>}</div><div className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{cards.map(([label, value, Icon]) => <div key={label} className="ariadne-panel p-4"><Icon className="size-4 text-violet-300" /><p className="mt-4 text-2xl font-semibold">{value}</p><p className="mt-1 text-xs text-slate-500">{label}</p></div>)}</div><p className="mt-5 text-xs text-slate-500">Progress refreshes automatically. Cached files are reused when their checksum is unchanged.</p></section>;
}
