"use client";
import { motion, useReducedMotion } from "framer-motion";
import { ArrowRight, BookOpen, Check, Compass, GitBranch, Layers3, Play, Rocket, Route, Sparkles } from "lucide-react";
import Link from "next/link";
import { useEffect, useState } from "react";

type Overview = { name: string; description?: string; primaryLanguage: string; framework?: string; architecture: string; technologies: string[]; metrics: Record<string, number | string>; map: { name: string; files: number; folders: string[]; dependencies: number }[]; hotspots: { title: string; entries: { name: string; value: number; detail: string }[] }[]; firstSteps: { title: string; detail: string; href: string }[] };
type JourneyStep = { title: string; eyebrow: string; description: string; icon: typeof Compass; href: string; action: string; highlights: string[] };

export function DeveloperJourney({ repositoryId }: { readonly repositoryId: string }) {
  const [overview, setOverview] = useState<Overview>(); const [step, setStep] = useState(0); const reduced = useReducedMotion();
  useEffect(() => { fetch(`/api/repositories/${repositoryId}/overview`).then(async (response) => response.ok && setOverview(await response.json())); }, [repositoryId]);
  if (!overview) return <div className="space-y-5"><div className="skeleton h-12 w-64" /><div className="skeleton h-[420px]" /></div>;
  const steps: JourneyStep[] = [
    { eyebrow: "Step 1 · Project summary", title: `Meet ${overview.name}`, description: overview.description ?? "Ariadne has mapped this repository into a focused learning path.", icon: Compass, href: `/repositories/${repositoryId}`, action: "Open overview", highlights: [`${overview.metrics["Total files"] ?? 0} files indexed`, overview.primaryLanguage, overview.framework ?? "Framework not detected"] },
    { eyebrow: "Step 2 · Architecture", title: `${overview.architecture} at a glance`, description: "This is the strongest structure signal from source paths and verified relationships. Use it as your map before changing a service.", icon: Layers3, href: `/repositories/${repositoryId}/architecture`, action: "Inspect architecture", highlights: [overview.architecture, `${overview.metrics.Dependencies ?? 0} verified dependencies`, `${overview.metrics["Circular dependencies"] ?? 0} circular signals`] },
    { eyebrow: "Step 3 · Business modules", title: "Learn the bounded areas", description: "These source areas are the best first approximation of how the repository divides responsibilities.", icon: GitBranch, href: `/repositories/${repositoryId}/files`, action: "Browse source areas", highlights: overview.map.slice(0, 4).map((area) => `${area.name}: ${area.files} files`) },
    { eyebrow: "Step 4 · Important services", title: "Start with connected services", description: "Highly connected symbols reveal the services that coordinate the most behavior. Read them before editing their callers.", icon: Sparkles, href: `/repositories/${repositoryId}/knowledge`, action: "Explore symbols", highlights: (overview.hotspots.find((group) => group.title === "Most connected")?.entries ?? []).slice(0, 4).map((entry) => `${entry.name}: ${entry.value} connections`) },
    { eyebrow: "Step 5 · Execution flow", title: "Trace verified paths", description: "Follow the architecture graph to understand how services collaborate. Ariadne only highlights relationships extracted from repository analysis.", icon: Route, href: `/repositories/${repositoryId}/architecture`, action: "Trace a path", highlights: (overview.hotspots.find((group) => group.title === "Highest fan-out")?.entries ?? []).slice(0, 3).map((entry) => `${entry.name}: ${entry.detail}`) },
    { eyebrow: "Step 6 · Where to start coding", title: "Choose a safe entry point", description: "Begin with the repository’s most concentrated module, then verify its dependencies before making the first change.", icon: Rocket, href: overview.firstSteps[0]?.href ?? `/repositories/${repositoryId}/files`, action: "Find your entry point", highlights: overview.firstSteps.slice(0, 2).map((item) => item.detail) },
    { eyebrow: "Step 7 · Recommended reading", title: "Build your working model", description: "Read these repository-backed areas in order. The AI Explain panel stays available if you want a grounded explanation while you explore.", icon: BookOpen, href: overview.firstSteps.at(-1)?.href ?? `/repositories/${repositoryId}/knowledge`, action: "Start reading", highlights: overview.firstSteps.map((item) => item.title) },
  ];
  const current = steps[step]; const Icon = current.icon; const complete = step === steps.length - 1;
  return <main className="mx-auto max-w-5xl pb-14"><header className="flex flex-wrap items-end justify-between gap-5"><div><p className="eyebrow">Developer journey</p><h1 className="page-title mt-2">Learn this repository with a thread to follow.</h1><p className="muted mt-3 max-w-2xl">A practical onboarding route generated from Ariadne’s repository evidence.</p></div><span className="status-chip bg-violet-400/10 text-violet-200">{step + 1} / {steps.length}</span></header><div className="mt-8 flex gap-1">{steps.map((item, index) => <button key={item.title} onClick={() => setStep(index)} className={`h-1.5 flex-1 rounded-full transition ${index <= step ? "bg-gradient-to-r from-violet-400 to-cyan-300" : "bg-slate-800"}`} aria-label={`Go to ${item.title}`} />)}</div><motion.section key={current.title} initial={reduced ? false : { opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: .24 }} className="mt-5 overflow-hidden rounded-[24px] border border-violet-400/15 bg-gradient-to-br from-violet-500/[.12] via-slate-900/75 to-cyan-400/[.06] p-6 sm:p-10"><div className="grid gap-8 lg:grid-cols-[1.15fr_.85fr]"><div><p className="eyebrow">{current.eyebrow}</p><h2 className="mt-3 text-3xl font-semibold tracking-tight text-slate-50">{current.title}</h2><p className="muted mt-4 max-w-xl">{current.description}</p><div className="mt-7 flex flex-wrap gap-3"><Link href={current.href as never} className="rounded-xl bg-cyan-400 px-4 py-3 text-sm font-semibold text-slate-950">{current.action} <ArrowRight className="ml-1 inline size-4" /></Link>{!complete && <button onClick={() => setStep((value) => value + 1)} className="rounded-xl border border-slate-500/40 px-4 py-3 text-sm font-medium text-slate-200">Continue</button>}</div></div><JourneyIllustration icon={<Icon className="size-9" />} highlights={current.highlights} /></div></motion.section>{complete ? <Completion repositoryId={repositoryId} overview={overview} /> : <section className="mt-5 ariadne-panel p-6"><p className="eyebrow">Up next</p><div className="mt-3 flex items-center justify-between gap-4"><div><p className="font-medium text-slate-100">{steps[step + 1].title}</p><p className="mt-1 text-sm text-slate-500">{steps[step + 1].description}</p></div><button onClick={() => setStep((value) => value + 1)} className="rounded-full bg-violet-400/10 p-2 text-violet-200"><ArrowRight className="size-4" /></button></div></section>}</main>;
}
function JourneyIllustration({ icon, highlights }: { readonly icon: React.ReactNode; readonly highlights: readonly string[] }) { return <div className="relative overflow-hidden rounded-2xl border border-white/[.08] bg-slate-950/35 p-5"><div className="absolute -right-10 -top-10 size-40 rounded-full bg-cyan-400/10 blur-3xl" /><div className="relative grid size-16 place-items-center rounded-2xl bg-gradient-to-br from-violet-400/25 to-cyan-300/15 text-cyan-100">{icon}</div><div className="relative mt-6 space-y-3">{highlights.length ? highlights.map((highlight, index) => <div key={`${highlight}-${index}`} className="flex items-center gap-3 rounded-xl border border-white/[.06] bg-white/[.03] px-3 py-2.5"><span className="grid size-5 place-items-center rounded-full bg-emerald-400/15 text-emerald-300"><Check className="size-3" /></span><p className="truncate text-sm text-slate-200">{highlight}</p></div>) : <p className="text-sm text-slate-500">Run repository analysis to reveal this journey step.</p>}</div></div>; }
function Completion({ repositoryId, overview }: { readonly repositoryId: string; readonly overview: Overview }) { const minutes = Math.max(35, Math.round(Number(overview.metrics["Total files"] ?? 0) * .7 + Number(overview.metrics.Dependencies ?? 0) * .2)); return <section className="mt-5 overflow-hidden rounded-[24px] border border-emerald-400/20 bg-gradient-to-br from-emerald-400/[.12] to-slate-900/70 p-7 text-center"><div className="mx-auto grid size-14 place-items-center rounded-full bg-emerald-400/15 text-emerald-200"><Check className="size-7" /></div><p className="eyebrow mt-5 text-emerald-300">Journey complete</p><h2 className="mt-2 text-2xl font-semibold">You now understand approximately 80% of the repository.</h2><p className="muted mx-auto mt-3 max-w-xl">Ariadne condensed the initial orientation work into a guided path grounded in this repository’s own symbols and relationships.</p><div className="mx-auto mt-6 max-w-xs rounded-xl border border-emerald-400/15 bg-slate-950/25 p-4"><p className="text-xs uppercase tracking-[.14em] text-slate-500">Estimated learning time saved</p><p className="mt-1 text-3xl font-semibold text-emerald-200">~{minutes} min</p></div><Link href={`/repositories/${repositoryId}/knowledge`} className="mt-6 inline-flex items-center gap-2 text-sm font-medium text-emerald-200">Keep exploring the knowledge base <Play className="size-4" /></Link></section>; }
