"use client";
import { FormEvent, useRef, useState } from "react";

type Citation = { id: string; label: string; path: string; line: number };
export function RepositoryAIChat({ repositoryId }: { readonly repositoryId: string }) {
  const [question, setQuestion] = useState(""); const [answer, setAnswer] = useState(""); const [citations, setCitations] = useState<Citation[]>([]); const [status, setStatus] = useState<"idle" | "thinking" | "streaming" | "error">("idle"); const [error, setError] = useState(""); const abort = useRef<AbortController | null>(null);
  const ask = async (event: FormEvent) => { event.preventDefault(); if (!question.trim()) return; abort.current?.abort(); const controller = new AbortController(); abort.current = controller; setAnswer(""); setCitations([]); setError(""); setStatus("thinking"); try { const response = await fetch(`/api/repositories/${repositoryId}/ai/chat`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ question }), signal: controller.signal }); if (!response.ok) throw new Error((await response.json()).error ?? "Ariadne could not answer this question."); const header = response.headers.get("x-ariadne-citations"); if (header) setCitations(JSON.parse(header)); if (!response.body) throw new Error("The response stream was unavailable."); setStatus("streaming"); const reader = response.body.getReader(); const decoder = new TextDecoder(); while (true) { const { value, done } = await reader.read(); if (done) break; setAnswer((current) => current + decoder.decode(value, { stream: true })); } setStatus("idle"); } catch (reason) { if ((reason as Error).name !== "AbortError") { setError(reason instanceof Error ? reason.message : "Ariadne could not answer this question."); setStatus("error"); } } };
  return <section className="ariadne-panel p-6"><p className="eyebrow">Grounded AI</p><h1 className="mt-1 text-2xl font-semibold">Ask about this repository</h1><p className="muted mt-2">Ariadne retrieves relevant symbols and responds only with repository evidence.</p><form onSubmit={ask} className="mt-6"><textarea value={question} onChange={(event) => setQuestion(event.target.value)} placeholder="Explain the authentication flow…" className="min-h-28 w-full rounded-xl border border-slate-700 bg-slate-950 p-4 text-sm outline-none focus:border-cyan-300" /><div className="mt-3 flex gap-3"><button className="rounded-lg bg-cyan-400 px-4 py-2 text-sm font-semibold text-slate-950">Ask Ariadne</button>{status !== "idle" && <button type="button" onClick={() => abort.current?.abort()} className="rounded-lg border border-slate-700 px-4 py-2 text-sm text-slate-300">Cancel</button>}</div></form>{status === "thinking" && <p className="mt-6 animate-pulse text-sm text-cyan-200">Understanding repository context…</p>}{answer && <article className="mt-6 rounded-xl border border-white/[.08] bg-white/[.025] p-5 whitespace-pre-wrap text-sm leading-7 text-slate-200">{answer}{status === "streaming" && <span className="ml-1 inline-block size-2 animate-pulse rounded-full bg-cyan-300" />}</article>}{citations.length > 0 && <div className="mt-5"><p className="eyebrow">Repository evidence</p><div className="mt-3 flex flex-wrap gap-2">{citations.map((citation) => <span key={citation.id} className="rounded-lg border border-violet-400/20 bg-violet-400/[.06] px-3 py-2 text-xs text-violet-100">{citation.label} · {citation.path}:{citation.line}</span>)}</div></div>}{error && <p className="mt-5 text-sm text-rose-300">{error}</p>}</section>;
}
